### ISSUE TITLE
BOM location

### ISSUE THREAD

**Issue by DAZHUANG2022** [mackieks/MaplePad#2]
This is great. I downloaded it. But the BOM list doesn't mark the locations. Hope you can mark them. Thanks

**Comment by mackieks** [comment]
Hi there! Glad you like it.

The hardware documentation is minimal because I have a new revision with some major improvements coming soon. In fact, the PCBs just arrived yesterday! Once I've assembled and tested the new board, I'll update the hardware folder with a complete BOM, gerbers, and assembly info, as well as updated firmware to support it. I wouldn't recommend building the old board-- the 0201 footprints are a little too small and don't work very well.

**Comment by DAZHUANG2022** [comment]
Hi this is really very good news. I also saw that 0201 is hard to solder by hand. Very looking forward to the new version. Thanks

**Comment by mackieks** [comment]
I've uploaded the new hardware revision as well as a complete BOM and assembly diagram to the 'hardware' folder. However, the software doesn't completely support the new board, so I can't recommend it for general use yet.

**Comment by DAZHUANG2022** [comment]
> I've uploaded the new hardware revision as well as a complete BOM and assembly diagram to the 'hardware' folder. However, the software doesn't completely support the new board, so I can't recommend it for general use yet.

Thank you I will continue to follow him Thank you for your efforts Looking forward to his new version
