### ISSUE TITLE
MaplePad (VMU) on a Badger 2040

### ISSUE THREAD

**Issue by kadern0** [mackieks/MaplePad#20]
Hi @mackieks, this is not an issue but a question. Do you think it would be possible to run this project (at least the VMU emulator) on a [Badger 2040](https://shop.pimoroni.com/products/badger-2040)?

Regards!

**Comment by mackieks** [comment]
Hi! The code will run on the Badger, but I only support SSD1306 and SSD1331 OLEDs for the VMU display right now. Porting the Badger's ePaper library wouldn't be hard, but even with partial refresh some games wouldn't look good due to the low display update rate. Case in point, Power Smash 2:

https://user-images.githubusercontent.com/49252894/227059879-80d3bab9-217f-49cf-a020-74a354a9a1b2.mp4  

Games that display static images or simple animations, like Rez, might be OK with partial refresh.

https://user-images.githubusercontent.com/49252894/227061105-1d1b73f7-dd9d-40ce-8873-35c2165c08cc.mp4

Also, MaplePad isn't a standalone 'VMU emulator'. So you need to be connected to a Dreamcast or other Maple host to get VMU images (unless you gut the codebase and feed in dummy packets or something). 

Keep in mind the Badger has a ton of onboard circuitry, so you'd have to remap pins in `maple.h` for the controller buttons, and cut traces and stuff for the ADC lines if you want joystick/trigger compatibility.

**Comment by kadern0** [comment]
Thank you for your response. Totally agree that that the e-ink display might not show the best results on games that make a lot of use of the VMU's display. My idea was more about connecting the Badger to the Dreamcast 'just' to save/load games and use the on board buttons to switch between memory pages. Would that  be hard to achieve?

**Comment by mackieks** [comment]
Got it. Wasn't sure what your use case was. Yes, that's doable.

You can connect the Badger to the P2/P3/P4 controller port and use its internal VMUs that way. The Dreamcast will register a controller being present on whichever port you choose, and you won't be able to connect an external controller to that port.

This is because retail software will only talk to subperipherals (VMU, rumble pack, microphone) if they are connected through a parent peripheral (controller or arcade stick). So you can't connect VMUs directly to the Dreamcast without a controller.

If you want to cycle pages with the Badger's buttons, update the `PAGE_BUTTON` macro in `maple.c` to the appropriate pin. The codebase is kinda broken right now, so base any edits off [commit b187916](https://github.com/mackieks/MaplePad/tree/b187916e5ac688214a89d33c4f908024896cdd28). 

I'd also recommend compiling an arcade stick binary (set these defines in `maple.h`) because otherwise, the code will read in garbage from the Badger's ADC pins (pic below), and the joystick and triggers will do weird things.
![image](https://user-images.githubusercontent.com/49252894/227084062-793ed73f-a1ff-4282-9bda-82032cedffed.png)
<img src="https://user-images.githubusercontent.com/49252894/227084013-8c004e67-931a-4a75-bdb0-643940985095.png" width="300">

At some point I want to develop a MaplePad-based "Super VMU" that you can plug into a stock controller for these sorts of use cases, but that's a long way off.

**Comment by mackieks** [comment]
Closing this for now, lemme know if you have any other questions!
